FROM node:22 AS builder

WORKDIR /app

COPY package*.json ./
RUN npm ci

COPY . .
RUN npm run build

FROM node:22-alpine

WORKDIR /app

ENV NODE_ENV=production
RUN addgroup -S app && adduser -S app -G app

COPY --from=builder /app/package*.json ./
RUN npm ci 

COPY --from=builder /app/dist ./dist

USER app

EXPOSE 5029

CMD ["node","dist/server.js"]